#!/usr/bin/expect -f

echo "Starting code-server remote..."

spawn   code-server \
            --accept-server-license-terms \
            --disable-telemetry \
            serve

expect {
  "What would you like to call this machine?" {
    send -- "$RUNPOD_POD_ID\r"
    exp_continue
  }
  eof
}
