FROM runpod/stable-diffusion:comfy-base-2.0.0

WORKDIR /workspace

ADD SDv1-5.ckpt /workspace/ComfyUI/models/checkpoints/v1-5-pruned-emaonly.ckpt
ADD SDv2-768.ckpt /workspace/ComfyUI/models/checkpoints
