#!/usr/bin/expect -f

set timeout -1
set runpod_pod_id $env(RUNPOD_POD_ID)

spawn code-server \
    --accept-server-license-terms \
    --disable-telemetry \
    serve

expect {
    "What would you like to call this machine?" {
        send -- "$runpod_pod_id\r"
        exp_continue
    }
    eof
}
