name: ComfyUI Development Build

on:
  workflow_dispatch:
  push:
    paths:
      - "official-templates/stable-diffusion-comfyui/**"
    branches-ignore:
      - main

jobs:
  dev:
    runs-on: ubuntu-latest-public-m
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update template README on RunPod
        env:
          RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
        uses: ./.github/actions/update-readme
        with:
          template_id: "runpod-comfy"
          template_path: "official-templates/stable-diffusion-comfyui"

      - name: Clear space to remove unused folders
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set environment variables
        run: |
          # Convert branch name to tag-friendly format (replace / with -)
          BRANCH_NAME=$(echo ${GITHUB_REF##refs/heads/} | sed 's/\//-/g')
          # Add dev- prefix to the branch name
          echo "RELEASE=dev-${BRANCH_NAME}" >> $GITHUB_ENV
          # Set environment variable to disable entitlements checks
          echo "BUILDX_BAKE_ENTITLEMENTS_FS=0" >> $GITHUB_ENV

      - name: Build and push the images to Docker Hub
        uses: docker/bake-action@v2
        with:
          files: ./official-templates/stable-diffusion-comfyui/docker-bake.hcl
          push: true
          set: |
            *.args.RELEASE=${{ env.RELEASE }}
            *.args.GITHUB_WORKSPACE=${{ github.workspace }}
