name: Compute Version

on:
  pull_request:
    paths:
      - ".github/actions/compute-version/**"
      - ".github/workflows/compute-version.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  detect-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: detect-bump unit tests
        run: bash .github/actions/compute-version/test_detect-bump.sh
