name: Compute Version

on:
  pull_request:
    paths:
      - ".github/actions/compute-version/**"
      - ".github/workflows/compute-version.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  detect-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: detect-bump unit tests
        run: bash .github/actions/compute-version/test_detect-bump.sh
