name: Hadolint-Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  hadolint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: official-templates/base/Dockerfile
            ignore: DL3006,DL3008,DL3013,DL3022
          - dockerfile: official-templates/pytorch/Dockerfile
            ignore: "DL3013,DL3006,DL3042"
          - dockerfile: official-templates/autoresearch/Dockerfile
            ignore: "DL3006"
          - dockerfile: helper-templates/verify-nccl/Dockerfile
            ignore: "DL3008"
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Lint Dockerfile
        uses: ./.github/actions/hadolint
        with:
          dockerfile: ${{ matrix.dockerfile }}
          failure-threshold: warning
          format: sarif
          output-file: hadolint.sarif
          ignore: ${{ matrix.ignore }}
      
      - name: Upload Hadolint SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e
        with:
          sarif_file: hadolint.sarif
          category: hadolint-${{ strategy.job-index }}
          