name: ROCm Image Build

on:
  push:
    paths:
      - ".github/workflows/rocm.yml"
      - "official-templates/rocm/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-rocm:
    runs-on: blacksmith-8vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Docker
        uses: ./.github/actions/docker-setup
        id: setup
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build rocm images
        uses: docker/bake-action@v6
        env:
          BUILDX_BAKE_ENTITLEMENTS_FS: 0
          RELEASE_SUFFIX: ${{ steps.setup.outputs.release-suffix }}
        with:
          source: .
          files: |
            official-templates/shared/versions.hcl
            official-templates/rocm/docker-bake.hcl
          push: true
